# Generated by Django 4.2.3 on 2023-07-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publicado'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='ano_construccion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='ImagenPrincipalPost'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.TextField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.tipotrabajo'),
        ),
    ]
